// Differential fuzz harness for the profile_version cross-line structural scan (issue #110). This is
// the build-time arbiter the plan calls for: a hand-rolled partial-YAML lexer has a long false-reject
// tail that only a large corpus, checked against a REAL YAML parser, can flush out. `scanStructure`'s
// only hard invariant is FALSE-REJECT-FREE — it must never call a document malformed that Ruby/Psych
// actually loads — so the one fatal assertion here is exactly that, run over thousands of generated
// fragments across every grammar dimension the design argues is safe.
//
// Ruby-gated: if `ruby -ryaml` isn't on PATH, every test in this file is skipped (`node --test` still
// passes clean) rather than failing — this harness is a developer/CI differential proof, not part of
// the shipped runtime contract (references/profile-validation.md documents the algorithm; this file
// documents that it was checked against ground truth, not that ground truth ships).
//
// Deterministic: the corpus is generated by a seeded PRNG (mulberry32 — no Math.random), so a failure
// reproduces byte-for-byte across runs and machines.

import test from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, writeFileSync, rmSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { readProfileVersion } from '../skills/enduser-handbook/assets/lib/profile-version.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));

// ---- ruby gate -----------------------------------------------------------------------------------

const RUBY_AVAILABLE = spawnSync('ruby', ['-ryaml', '-e', '1'], { stdio: 'ignore' }).status === 0;

// ---- deterministic seeded PRNG (mulberry32 — no Math.random anywhere in this file) ----------------

function mulberry32(seed) {
  let a = seed >>> 0;
  return function rand() {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const SEED = 0x50524f46; // 'PROF' — fixed, so every run generates the identical corpus
const rand = mulberry32(SEED);
const pick = (arr) => arr[Math.floor(rand() * arr.length)];
const int = (lo, hi) => lo + Math.floor(rand() * (hi - lo + 1));

// ---- corpus generation: every fragment is a full doc starting "profile_version: 1" ----------------
//
// Dimensions covered (each one the design's false-reject-free argument leans on, or a workflow-round
// fix that previously produced a real false-reject — see references/profile-validation.md):
//   (i)   compact-colon flow maps: {"k":"v"} / {"k":"]"} / {'k':'}'} / nested [{"k":"]"}]
//   (ii)  seq-entry plain-scalar fold: "- value" then a more-indented "- [x" / "- \"x" / "- *x" / bare
//   (iii) comment lines with a colon + unbalanced bracket/quote/alias, incl. the shipped
//         "# internal: []" weaponized to "# internal: [AuthUser"
//   plus: block-scalar grids (both modifier orders, header-junk, seq/nested-seq introducers), node
//   property ordering, flow plain scalars with mid-token quotes, tab-separated flow comments,
//   multi-line quotes/flows, '' escapes, a flow/quote continuation flush to COLUMN 0 (the Step 4
//   shape-allowlist gap this build also fixed), shipped-example mutations, and unicode fragments.

const frags = [];
const labels = [];
function add(label, body) {
  frags.push('profile_version: 1\n' + body);
  labels.push(label);
}
// Same corpus, but the raw document is supplied verbatim (used for fragments whose FIRST line is not
// `profile_version: 1` — e.g. a leading document marker `---` must precede the version key).
function addRaw(label, doc) {
  frags.push(doc);
  labels.push(label);
}

// (i) compact-colon flow maps
const compactMapVals = ['v', ']', '[', '}', '{', ':', ',', '*x', '&a 1'];
for (const cv of compactMapVals) {
  add(`compact-dq ${cv}`, `note: {"x":"${cv}"}\n`);
  add(`compact-sq ${cv}`, `note: {'x':'${cv}'}\n`);
  add(`compact-nested ${cv}`, `note: [{"x":"${cv}"}]\n`);
  add(`compact-2elt ${cv}`, `note: {"a":"1","x":"${cv}"}\n`);
}

// (ii) seq-entry plain-scalar fold
const seqFolds = ['[x', '"x', "'x", '*x', '[oops', '{oops'];
for (const sf of seqFolds) {
  add(`seqfold ${sf}`, `note:\n  - value\n    - ${sf}\n`);
  add(`seqfold-deep ${sf}`, `outer:\n  note:\n    - value\n      - ${sf}\n`);
  add(`seqfold-bare ${sf}`, `list:\n  - item\n    ${sf}\n`);
}

// (iii) comment lines with a colon + unbalanced/alias
const commentTails = ['[a, b, c', '"quote it', '*x', '[AuthUser', '{oops', "'q"];
for (const ct of commentTails) {
  add(`comment-colon ${ct}`, `# see: ${ct}\n`);
  add(`comment-colon-indent ${ct}`, `a:\n  # comment: ${ct}\n  b: 1\n`);
  add(`comment-colon-nested ${ct}`, `capture:\n  role_flags:\n    admin:\n      - AuthAdminUser\n    # internal: ${ct}\n`);
}

// block scalar grids: both modifier orders, direct + nested seq introducers, header-junk
const modifiers = ['', '2', '-', '+', '-2', '2-', '+2', '2+', '--', '99'];
for (const style of ['|', '>']) {
  for (const mod of modifiers) {
    add(`block ${style}${mod}`, `note: ${style}${mod}\n  #weird\n  line two\n  [ open forever\nb: 1\n`);
    add(`block-seq ${style}${mod}`, `note:\n  - ${style}${mod}\n    #weird\n    [ open forever\nb: 1\n`);
    add(`block-seq2 ${style}${mod}`, `note:\n  - - ${style}${mod}\n      #weird\n      [ open forever\nb: 1\n`);
  }
}
add('header-junk pipe', 'note: | pipe\n');
add('header-junk gt', 'note: > text more\n');

// node-property ordering
add('tag-then-anchor', 'k: !!str &a hello\n');
add('anchor-then-tag', 'k: &a !!str hello\n');
add('anchor-flow', 'k: &a [1, 2]\nm: *a\n');
add('tag-quote', 'k: !!str "hi"\n');

// anchor gate (ped-ant review finding): the "any & anywhere" gate over-triggers on prose ("R&D",
// "AT&T") and silently disables mechanism C for the whole document. Narrowed to exclude a "&"
// immediately preceded by a word character — a real anchor introducer always sits at a token-start
// (whitespace / flow-indicator / line-start), never glued to a preceding letter/digit. Every real
// anchor position below must still resolve its alias (ruby-OK, must stay ok); every prose-"&"-with-an-
// undefined-alias fragment must now be CAUGHT (ruby-BadAlias/SyntaxError, was a silent miss before).
add('anchor-block-key', 'a: &x 1\nb: *x\n');
add('anchor-seq-entry', 'note:\n  - &x 1\n  - *x\n');
add('anchor-flow-seq', 'm: [&x 1, *x]\n');
add('anchor-flow-map-value', 'm: {a: &x 1, b: *x}\n');
add('anchor-flow-map-compact', 'm: {"a":&x 1, "b":*x}\n');
add('anchor-tag-then-anchor-resolved', 'a: !!str &x hi\nb: *x\n');
add('anchor-then-tag-resolved', 'a: &x !!str hi\nb: *x\n');
add('anchor-nested-deep', 'outer:\n  inner:\n    a: &x 1\n    b: *x\n');
add('prose-amp-RandD-undefined-alias', 'description: R&D\nglob: *.md\n');
add('prose-amp-ATandT-undefined-alias', 'vendor: AT&T\nx: *undef\n');
add('prose-amp-comment-undefined-alias', '# R&D department\nx: *undef\n');
add('prose-amp-QandA-no-alias', 'faq: Q&A\n');
add('prose-amp-no-alias-alone', 'description: R&D\n');

// compact and nested seq indentation (nested under a top-level key so the fragment survives the
// column-0 shape allowlist and actually reaches scanStructure through the full pipeline)
add('compact-key', 'note:\n  - key: value\n');
add('nested-compact-key', 'note:\n  - - key: value\n');
add('compact-key-block', 'note:\n  - key: |\n      body\n      [never closes\nb: 1\n');
add('nested-compact-key-block', 'note:\n  - - key: |\n        body\n        [never closes\nb: 1\n');

// flow plain scalars w/ mid-token quotes; tab-separated flow comment
add('flow-mid-quote', 'a: [abc"unterminated]\n');
add('flow-mid-squote', "a: [abc'unterminated]\n");
add('flow-tab-comment', 'a: [1,\t# }]\nb: 1\n');

// multi-line quotes / flows; '' escape
add('multiline-dq', 'a: "line one\n  line two"\nb: 2\n');
add('multiline-sq', "a: 'line one\n  line two'\nb: 2\n");
add('multiline-flow', 'a: [1,\n  2,\n  3]\nb: 2\n');
add('sq-escape', "a: 'it''s fine'\nb: 2\n");
add('dq-escape', 'a: "she said \\"hi\\""\nb: 2\n');
add('dq-backslash', 'a: "back\\\\slash"\nb: 2\n');
add('flow-wrap-plain', 'a: [abc\n  def]\n');

// a flow/quote continuation flush to COLUMN 0 (the Step 4 shape-allowlist fix this build shipped)
add('col0-flow-close', 'a: [1,\n2]\n');
add('col0-flow-close-deeper', 'a: [1, [2,\n3]]\n');
add('col0-dq-close', 'a: "l1\nl2"\nb: 2\n');
add('col0-sq-close', "a: 'l1\nl2'\nb: 2\n");
add('col0-flow-multi', 'a: [1,\n2,\n3]\nb: 2\n');
add('col0-flow-unterminated', 'a: [1,\n2\n');
add('col0-dq-unterminated', 'a: "l1\nl2\n');
add('col0-mixed', 'a: ["x",\n"y"]\nb: [3,\n4]\n');

// mismatched delimiter types — untyped floor never catches these (accepted false-negative), must not
// crash and must never falsely reject either
add('mismatch-bracket-brace', 'a: [1, 2}\n');
add('mismatch-brace-bracket', 'a: {x: 1]\n');

// shipped-example mutations
const shipped = `stack:
  backend:
    type: laravel
    route_globs:
      - "routes/web/*.php"
      - "routes/admin/*.php"
    api_url_prefix: "/api/v1"
capture:
  role_flags:
    admin:
      - AuthAdminUser
    # internal: []
    # external: []
  command: |
    docker compose run --rm \\
      --user "$(id -u):$(id -g)" \\
      app npx playwright test
  auth_role_enum: [admin, internal, external]
`;
add('shipped-verbatim', shipped);
add('shipped-drop-quote', shipped.replace('"routes/web/*.php"', '"routes/web/*.php'));
add('shipped-drop-bracket', shipped.replace('[admin, internal, external]', '[admin, internal, external'));
add('shipped-insert-alias', shipped.replace('type: laravel', 'type: *undefined'));
add('shipped-insert-anchor', shipped.replace('type: laravel', 'type: &t laravel'));
add('shipped-slip-indent', shipped.replace('      - AuthAdminUser', '     - AuthAdminUser'));
add('shipped-truncate-flow', shipped.replace('[admin, internal, external]', '[admin, internal'));
add('shipped-weaponize-comment', shipped.replace('# internal: []', '# internal: [AuthUser'));

// a comment starting with NO space right after a flow closer (post-#116 review round): once the
// outermost flow node closes, lexFlowChars must stop lexing the rest of the line — a `#` glued
// directly onto `]`/`}` is still a comment start even with no preceding whitespace, and its content
// (however bracket-shaped) must never be treated as live flow again. Closer type × tail, both at the
// top level and nested under a key, so the fragment exercises this dimension through the full
// column-0-shape-allowlist pipeline too.
const flowCloseShapes = ['[1]', '[]', '{}', '{a: 1}', '[[1]]'];
const flowCloseTails = ['#[', '#{', '#a: [b', '#TODO: see [42', '# balanced comment', ' #[']; // last two: controls
for (const closer of flowCloseShapes) {
  for (const tail of flowCloseTails) {
    add(`flowclose ${closer}${tail}`, `note: ${closer}${tail}\n`);
    add(`flowclose-nested ${closer}${tail}`, `outer:\n  note: ${closer}${tail}\n  b: 1\n`);
  }
}

// unicode-aware fragments
const NBSP = String.fromCharCode(0xa0);
const ASTRAL = String.fromCodePoint(0x1f600);
const EURO = '€';
const COMBINING = 'e' + String.fromCharCode(0x0301); // e + combining acute accent
add('unicode-nbsp-value', `a: "value${NBSP}here"\n`);
add('unicode-astral-value', `a: "${ASTRAL}"\n`);
add('unicode-euro', `currency: "${EURO}"\n`);
add('unicode-combining', `name: "${COMBINING}"\n`);

// PR #126/#127 snake_case must-accepts: a tab INSIDE scalar content (block/quoted/flow/plain), a
// leading/trailing document marker, and a `? snake_case` explicit key. Every one is loaded by Psych as
// a single {profile_version: 1, ...} document (verified vs Psych 3.1.0), so the post-fix scan must NOT
// reject any — assertion 1 (false-reject-free) is the gate. TAB is built with fromCharCode so the code
// point under test is unambiguous. Do NOT add non-snake_case-key, leading-zero, directive, or quoted-
// key fragments HERE — those are documented halts and live in the broad corpus below.
const TAB = String.fromCharCode(0x09);
add('tab-content-block', `command: |\n  base\n  ${TAB}more\n`);
add('tab-content-quoted', `name: "abc\n  ${TAB}def"\n`);
add('tab-content-flow', `route_globs: [a,\n  ${TAB}b]\n`);
add('tab-content-plain', `note: abc\n  ${TAB}def\n`);
add('marker-trailing-doc-end', '...\n');
add('explicit-key-snake', '? some_key\n: some_value\n');
addRaw('marker-leading-doc-start', '---\nprofile_version: 1\n');
addRaw('marker-leading-doc-start-comment', '--- # hi\nprofile_version: 1\n');

// version-aware document-marker fuzz: a valid v1 profile wrapped in every combination of an optional
// leading `---` (bare or with a spaced comment) and an optional trailing `...` (with or without a
// trailing comment). Each is a single document Psych loads as {profile_version: 1, language: ...}, so
// the scan must accept them all (assertion 1) AND still read version 1 (assertion 2) regardless of the
// surrounding markers — a marker must never shift which key is treated as the version.
const leadMarkers = ['', '---\n', '--- # doc\n'];
const trailMarkers = ['', '...\n', '...\n# trailing comment\n'];
let markerFuzz = 0;
for (const lead of leadMarkers) {
  for (const trail of trailMarkers) {
    addRaw(`marker-fuzz-${markerFuzz}`, `${lead}profile_version: 1\nlanguage:\n  code: de\n${trail}`);
    markerFuzz += 1;
  }
}

// randomized combinatorial generation across the same dimensions, seeded and reproducible
const dashPrefixes = ['', '- ', '- - ', '- - - '];
const seps = [': ', ':\t'];
const valueOpeners = ['[', '{', '"', "'", '*', '|', '>', 'plain'];
const closers = { '[': ']', '{': '}', '"': '"', "'": "'" };
for (let i = 0; i < 2200; i += 1) {
  const dash = pick(dashPrefixes);
  const sep = pick(seps);
  const opener = pick(valueOpeners);
  const closed = rand() < 0.5;
  let value;
  if (opener === 'plain') {
    value = pick(['hello', 'a*b', 'http://x:8080', 'text with spaces', '5" pipe', 'he said "hi"']);
  } else if (opener === '|' || opener === '>') {
    const mod = pick(['', '2', '-', '+']);
    value = `${opener}${mod}\n${' '.repeat(int(2, 8))}body line\n${' '.repeat(int(2, 8))}[ maybe open\n`;
  } else if (opener === '*') {
    value = closed ? 'x' : '';
  } else {
    const inner = pick(['1, 2', '"a", "b"', "'a', 'b'", '"x":"y"', 'a, [nested', '1, 2, 3']);
    value = closed ? `${opener}${inner}${closers[opener]}` : `${opener}${inner}`;
  }
  let doc;
  if (dash) {
    // nest under a top-level key so the fragment survives the column-0 shape allowlist and actually
    // reaches scanStructure through the full readProfileVersion pipeline (a bare "- ..." at column 0
    // is rejected earlier, for unrelated and already-proven-safe reasons).
    doc = `note:\n  ${dash}${value}\nb: 1\n`;
  } else if (rand() < 0.5) {
    doc = `k${sep}${value}\nb: 1\n`;
  } else {
    doc = `outer:\n  k${sep}${value}\n  b: 1\n`;
  }
  add(`rand${i}`, doc);
}

// ---- broad corpus: frags + documented-residual / wrong-version-guard shapes -----------------------
//
// Assertion 2 (never-wrong-version) and assertion 3 (multi-document halt) run over this BROADER corpus.
// It adds shapes that are legitimately halted (or ok-on-parse-invalid) and therefore CANNOT live in the
// false-reject-free assertion-1 corpus: leading-zero + unsafe integers (each a wrong-version hole the
// #127 guards close), a mismatched flow (ok-on-parse-invalid), and multi-document streams (must halt).
// These are seeded explicitly so a regression that drops any single guard trips assertion 2 or 3:
//   - drop the leading-zero guard  -> `010` scans unsupported/10 while Psych reads octal 8   (10 != 8)
//   - drop the leading-zero guard  -> `0777` scans unsupported/777 while Psych reads octal 511 (777 != 511)
//   - drop the unsafe-integer guard-> `9007199254740993` scans .../...992 while Psych reads ...993
//   - accept a multi-doc stream    -> reads a version from a stream Psych splits into >= 2 documents
const broadFrags = frags.slice();
const broadLabels = labels.slice();
function broadAdd(label, doc) {
  broadFrags.push(doc);
  broadLabels.push(label);
}
broadAdd('num-leading-zero-010', 'profile_version: 010\n');
broadAdd('num-leading-zero-0777', 'profile_version: 0777\n');
broadAdd('num-unsafe-2p53p1', 'profile_version: 9007199254740993\n');
broadAdd('num-unsafe-2p53', 'profile_version: 9007199254740992\n');
broadAdd('mismatch-flow-ok-on-parse-invalid', 'profile_version: 1\na: [1, 2}\n');
broadAdd('multidoc-separator', 'profile_version: 1\n---\nprofile_version: 2\n');
broadAdd('multidoc-leading', '---\nprofile_version: 1\n---\nother: 2\n');

// ---- oracle: batch every fragment through ONE ruby process ----------------------------------------

// Per fragment the oracle emits one TAB-separated line: `index\tverdict\tpv\tmeaningful` where
//   verdict    = OK | RAISE  (Psych.load succeeded / raised)
//   pv         = the DECIMAL STRING of profile_version when Psych.load is a Hash whose profile_version
//                is an Integer, else empty. CRITICAL: emitted as a string (.to_s), never a JSON number,
//                so a value like 9007199254740993 survives the Ruby->JS crossing byte-exact instead of
//                rounding to ...992 and masking a real wrong-version mismatch (assertion 2).
//   meaningful = the number of NON-empty documents Psych.parse_stream splits the input into (a bare
//                empty plain scalar with no tag/anchor is not meaningful), or -1 if parse_stream raised.
const ORACLE_SCRIPT = `
require 'yaml'
require 'json'
def meaningful_count(s)
  stream = Psych.parse_stream(s)
  stream.children.count do |doc|
    root = doc.root
    empty = root.nil? ||
      (root.is_a?(Psych::Nodes::Scalar) && root.value == '' &&
       (root.respond_to?(:plain) ? root.plain : true) &&
       root.tag.nil? && (root.anchor.nil? || root.anchor == ''))
    !empty
  end
rescue Exception
  -1
end
frags = JSON.parse(File.read(ARGV[0]))
out = []
frags.each_with_index do |s, i|
  begin
    doc = Psych.load(s)
    pv = (doc.is_a?(Hash) && doc['profile_version'].is_a?(Integer)) ? doc['profile_version'].to_s : ''
    out << "#{i}\\tOK\\t#{pv}\\t#{meaningful_count(s)}"
  rescue Exception => e
    out << "#{i}\\tRAISE\\t\\t#{meaningful_count(s)}"
  end
end
puts out.join("\\n")
`;

function runOracle(fragments) {
  const dir = mkdtempSync(join(tmpdir(), 'profile-version-differential-'));
  try {
    const corpusPath = join(dir, 'corpus.json');
    const scriptPath = join(dir, 'oracle.rb');
    writeFileSync(corpusPath, JSON.stringify(fragments));
    writeFileSync(scriptPath, ORACLE_SCRIPT);
    const result = spawnSync('ruby', [scriptPath, corpusPath], {
      encoding: 'utf8',
      maxBuffer: 1024 * 1024 * 64,
    });
    assert.equal(result.status, 0, `ruby oracle failed: ${result.stderr}`);
    const oracle = new Array(fragments.length);
    for (const line of result.stdout.trim().split('\n')) {
      const parts = line.split('\t');
      const idx = Number(parts[0]);
      oracle[idx] = {
        ok: parts[1] === 'OK', // Psych.load did not raise
        pv: parts[2] ? parts[2] : null, // integer profile_version as a decimal STRING, or null
        meaningful: Number(parts[3]), // parse_stream non-empty document count, or -1 (raised)
      };
    }
    return oracle;
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

// Run the Ruby oracle ONCE over the BROAD corpus (a superset of `frags`), memoized so all three fatal
// assertions below share a single ruby spawn. Kept inside a getter (not a module-level const) so a
// ruby/oracle failure fails a test rather than crashing module load; only the ruby-gated tests call it.
let oracleCache;
function getOracle() {
  if (oracleCache === undefined) oracleCache = runOracle(broadFrags);
  return oracleCache;
}

// ---- fatal assertions ------------------------------------------------------------------------------

// Assertion 1 — FALSE-REJECT-FREE: over the snake_case must-accept corpus (`frags`), the scan must
// never call `malformed` a document Psych actually loads. `broadFrags` shares indices [0, frags.length)
// with `frags`, so oracle[i] lines up here.
test('differential fuzz: zero false-rejects across the snake_case must-accept corpus', { skip: !RUBY_AVAILABLE }, () => {
  const oracle = getOracle();
  const violations = [];
  for (let i = 0; i < frags.length; i += 1) {
    const r = readProfileVersion(frags[i]);
    if (r.status === 'malformed' && oracle[i].ok) {
      violations.push({ label: labels[i], message: r.message, fragment: frags[i] });
    }
  }
  if (violations.length > 0) {
    const detail = violations
      .slice(0, 10)
      .map((v) => `  [${v.label}] ${v.message}\n    fragment=${JSON.stringify(v.fragment)}`)
      .join('\n');
    assert.fail(`${violations.length} false-reject(s) out of ${frags.length} fragments:\n${detail}`);
  }
  assert.equal(violations.length, 0);
});

// Assertion 2 — NEVER-WRONG-VERSION (the hard invariant): whenever the scan returns ok/unsupported with
// version V and Psych.load reads a Hash with an Integer profile_version P, V must equal P. Compared as
// decimal STRINGS: the oracle emits P via .to_s and V is <= Number.MAX_SAFE_INTEGER post-guard, so
// String(V) is its exact decimal form — a JSON-number transport would round and mask the very mismatch
// this guards. Does NOT fire on ok-on-parse-invalid (Psych raise => not a Hash => oracle.pv is null).
test('differential fuzz: never returns a version different from Psych (the hard invariant)', { skip: !RUBY_AVAILABLE }, () => {
  const oracle = getOracle();
  const violations = [];
  for (let i = 0; i < broadFrags.length; i += 1) {
    const r = readProfileVersion(broadFrags[i]);
    if ((r.status === 'ok' || r.status === 'unsupported') && oracle[i].ok && oracle[i].pv !== null) {
      const scanV = String(r.version);
      if (scanV !== oracle[i].pv) {
        violations.push({ label: broadLabels[i], scanV, psychV: oracle[i].pv, fragment: broadFrags[i] });
      }
    }
  }
  if (violations.length > 0) {
    const detail = violations
      .slice(0, 10)
      .map((v) => `  [${v.label}] scan=${v.scanV} psych=${v.psychV}\n    fragment=${JSON.stringify(v.fragment)}`)
      .join('\n');
    assert.fail(`${violations.length} wrong-version violation(s):\n${detail}`);
  }
  assert.equal(violations.length, 0);
});

// Assertion 3 — MULTI-DOCUMENT MUST HALT: any input Psych.parse_stream splits into >= 2 meaningful
// documents must not yield ok/unsupported — a reader cannot safely pick which document's version to
// trust, so it halts. (`meaningful === -1` means parse_stream raised and is excluded from this bucket.)
test('differential fuzz: any multi-document stream (>= 2 meaningful docs) halts', { skip: !RUBY_AVAILABLE }, () => {
  const oracle = getOracle();
  const violations = [];
  for (let i = 0; i < broadFrags.length; i += 1) {
    if (oracle[i].meaningful >= 2) {
      const r = readProfileVersion(broadFrags[i]);
      if (r.status === 'ok' || r.status === 'unsupported') {
        violations.push({ label: broadLabels[i], status: r.status, version: r.version, fragment: broadFrags[i] });
      }
    }
  }
  if (violations.length > 0) {
    const detail = violations
      .slice(0, 10)
      .map((v) => `  [${v.label}] scan=${v.status}/${v.version}\n    fragment=${JSON.stringify(v.fragment)}`)
      .join('\n');
    assert.fail(`${violations.length} multi-doc-not-halted violation(s):\n${detail}`);
  }
  assert.equal(violations.length, 0);
});

test('differential fuzz: corpus size is large enough to be a meaningful gate', { skip: !RUBY_AVAILABLE }, () => {
  assert.ok(frags.length >= 2000, `corpus has only ${frags.length} fragments, expected >= 2000`);
});

test('differential fuzz: coverage — the known-invalid A/C representatives are still flagged', { skip: !RUBY_AVAILABLE }, () => {
  const mustFlag = {
    'unterminated flow (A1)': 'profile_version: 1\nroute_globs: ["a", "b"\n',
    'unterminated double quote (A3)': 'profile_version: 1\nname: "u\n',
    'unterminated single quote (A4)': "profile_version: 1\nsep: 'a\n",
    'undefined alias (C2 glob)': 'profile_version: 1\nglob: *.md\n',
    'undefined alias (C4 extra)': 'profile_version: 1\nextra: *undef\n',
    'undefined alias (C9 bare star)': 'profile_version: 1\nnote: * foo\n',
    'flow continuation, unterminated at column 0': 'profile_version: 1\na: [1,\n2\n',
    'undefined alias behind a prose "&" (anchor-gate narrowing)': 'profile_version: 1\ndescription: R&D\nglob: *.md\n',
  };
  for (const [label, doc] of Object.entries(mustFlag)) {
    const r = readProfileVersion(doc);
    assert.equal(r.status, 'malformed', `${label} did not get flagged: ${JSON.stringify(r)}`);
    assert.match(r.message, /structural:/, `${label} was flagged for a non-structural reason: ${r.message}`);
  }

  // numeric-guard representatives (#127) — halt with a NON-structural message (leading-zero / too
  // large). `010` is the octal wrong-version case; 2^53+1 is the unsafe-integer rounding case.
  const numericHalts = {
    'leading-zero octal (010)': ['profile_version: 010\n', /leading-zero/],
    'unsafe integer 2^53+1 (9007199254740993)': ['profile_version: 9007199254740993\n', /too large/],
  };
  for (const [label, [doc, needle]] of Object.entries(numericHalts)) {
    const r = readProfileVersion(doc);
    assert.equal(r.status, 'malformed', `${label} did not halt: ${JSON.stringify(r)}`);
    assert.match(r.message, needle, `${label} halted for the wrong reason: ${r.message}`);
  }
});

// Coverage — PR #126/#127 representatives keep their verdicts (scan-only, so NOT ruby-gated). These
// pair with the false-reject / never-wrong-version fuzz above: a tab in scalar CONTENT and a leading
// marker are accepted; an explicit `? profile_version` key and a tab in STRUCTURAL indentation halt.
// The structural-tab must-flags are the inverse of the tab-content must-accepts — a tab that a real
// YAML parser rejects (Psych raises) must still stop the scan.
test('differential fuzz: coverage — #126/#127 marker/tab/explicit-key representatives keep verdicts', () => {
  const mustAccept = {
    'tab in block-scalar content': 'profile_version: 1\ncommand: |\n  base\n  \tmore\n',
    'leading document-start marker': '---\nprofile_version: 1\n',
    'trailing document-end marker': 'profile_version: 1\n...\n',
  };
  for (const [label, doc] of Object.entries(mustAccept)) {
    const r = readProfileVersion(doc);
    assert.equal(r.status, 'ok', `${label} was not accepted: ${JSON.stringify(r)}`);
    assert.equal(r.version, 1);
  }
  const mustHalt = {
    'explicit "? profile_version" key': '? profile_version\n: 1\n',
    'structural tab: tab-indented child key': 'profile_version: 1\nfoo:\n\tbar: 1\n',
    'structural tab: tab several levels deep': 'profile_version: 1\nstack:\n  backend:\n    type: laravel\n\tapi_url_prefix: "/api/v1"\n',
    // Trailing bare `---` is a SANCTIONED halt, NOT a must-accept: Psych loads it as {profile_version: 1}
    // (one document), but the scan cannot cheaply tell a trailing separator from a real second document,
    // so it conservatively halts. It lives ONLY here — never in the false-reject-free `frags` corpus,
    // where it would (correctly) trip assertion 1 since Psych loads it. Contrast with trailing `...` (ok).
    'trailing bare "---" (sanctioned multi-doc-separator halt)': 'profile_version: 1\n---\n',
  };
  for (const [label, doc] of Object.entries(mustHalt)) {
    const r = readProfileVersion(doc);
    assert.equal(r.status, 'malformed', `${label} did not halt: ${JSON.stringify(r)}`);
  }
});
