// Differential fuzz harness for the profile_version cross-line structural scan (issue #110). This is
// the build-time arbiter the plan calls for: a hand-rolled partial-YAML lexer has a long false-reject
// tail that only a large corpus, checked against a REAL YAML parser, can flush out. `scanStructure`'s
// only hard invariant is FALSE-REJECT-FREE — it must never call a document malformed that Ruby/Psych
// actually loads — so the one fatal assertion here is exactly that, run over thousands of generated
// fragments across every grammar dimension the design argues is safe.
//
// Ruby-gated: if `ruby -ryaml` isn't on PATH, every test in this file is skipped (`node --test` still
// passes clean) rather than failing — this harness is a developer/CI differential proof, not part of
// the shipped runtime contract (references/profile-validation.md documents the algorithm; this file
// documents that it was checked against ground truth, not that ground truth ships).
//
// Deterministic: the corpus is generated by a seeded PRNG (mulberry32 — no Math.random), so a failure
// reproduces byte-for-byte across runs and machines.

import test from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, writeFileSync, rmSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { readProfileVersion } from '../skills/enduser-handbook/assets/lib/profile-version.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));

// ---- ruby gate -----------------------------------------------------------------------------------

const RUBY_AVAILABLE = spawnSync('ruby', ['-ryaml', '-e', '1'], { stdio: 'ignore' }).status === 0;

// ---- deterministic seeded PRNG (mulberry32 — no Math.random anywhere in this file) ----------------

function mulberry32(seed) {
  let a = seed >>> 0;
  return function rand() {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const SEED = 0x50524f46; // 'PROF' — fixed, so every run generates the identical corpus
const rand = mulberry32(SEED);
const pick = (arr) => arr[Math.floor(rand() * arr.length)];
const int = (lo, hi) => lo + Math.floor(rand() * (hi - lo + 1));

// ---- corpus generation: every fragment is a full doc starting "profile_version: 1" ----------------
//
// Dimensions covered (each one the design's false-reject-free argument leans on, or a workflow-round
// fix that previously produced a real false-reject — see references/profile-validation.md):
//   (i)   compact-colon flow maps: {"k":"v"} / {"k":"]"} / {'k':'}'} / nested [{"k":"]"}]
//   (ii)  seq-entry plain-scalar fold: "- value" then a more-indented "- [x" / "- \"x" / "- *x" / bare
//   (iii) comment lines with a colon + unbalanced bracket/quote/alias, incl. the shipped
//         "# internal: []" weaponized to "# internal: [AuthUser"
//   plus: block-scalar grids (both modifier orders, header-junk, seq/nested-seq introducers), node
//   property ordering, flow plain scalars with mid-token quotes, tab-separated flow comments,
//   multi-line quotes/flows, '' escapes, a flow/quote continuation flush to COLUMN 0 (the Step 4
//   shape-allowlist gap this build also fixed), shipped-example mutations, and unicode fragments.

const frags = [];
const labels = [];
function add(label, body) {
  frags.push('profile_version: 1\n' + body);
  labels.push(label);
}

// (i) compact-colon flow maps
const compactMapVals = ['v', ']', '[', '}', '{', ':', ',', '*x', '&a 1'];
for (const cv of compactMapVals) {
  add(`compact-dq ${cv}`, `note: {"x":"${cv}"}\n`);
  add(`compact-sq ${cv}`, `note: {'x':'${cv}'}\n`);
  add(`compact-nested ${cv}`, `note: [{"x":"${cv}"}]\n`);
  add(`compact-2elt ${cv}`, `note: {"a":"1","x":"${cv}"}\n`);
}

// (ii) seq-entry plain-scalar fold
const seqFolds = ['[x', '"x', "'x", '*x', '[oops', '{oops'];
for (const sf of seqFolds) {
  add(`seqfold ${sf}`, `note:\n  - value\n    - ${sf}\n`);
  add(`seqfold-deep ${sf}`, `outer:\n  note:\n    - value\n      - ${sf}\n`);
  add(`seqfold-bare ${sf}`, `list:\n  - item\n    ${sf}\n`);
}

// (iii) comment lines with a colon + unbalanced/alias
const commentTails = ['[a, b, c', '"quote it', '*x', '[AuthUser', '{oops', "'q"];
for (const ct of commentTails) {
  add(`comment-colon ${ct}`, `# see: ${ct}\n`);
  add(`comment-colon-indent ${ct}`, `a:\n  # comment: ${ct}\n  b: 1\n`);
  add(`comment-colon-nested ${ct}`, `capture:\n  role_flags:\n    admin:\n      - AuthAdminUser\n    # internal: ${ct}\n`);
}

// block scalar grids: both modifier orders, direct + nested seq introducers, header-junk
const modifiers = ['', '2', '-', '+', '-2', '2-', '+2', '2+', '--', '99'];
for (const style of ['|', '>']) {
  for (const mod of modifiers) {
    add(`block ${style}${mod}`, `note: ${style}${mod}\n  #weird\n  line two\n  [ open forever\nb: 1\n`);
    add(`block-seq ${style}${mod}`, `note:\n  - ${style}${mod}\n    #weird\n    [ open forever\nb: 1\n`);
    add(`block-seq2 ${style}${mod}`, `note:\n  - - ${style}${mod}\n      #weird\n      [ open forever\nb: 1\n`);
  }
}
add('header-junk pipe', 'note: | pipe\n');
add('header-junk gt', 'note: > text more\n');

// node-property ordering
add('tag-then-anchor', 'k: !!str &a hello\n');
add('anchor-then-tag', 'k: &a !!str hello\n');
add('anchor-flow', 'k: &a [1, 2]\nm: *a\n');
add('tag-quote', 'k: !!str "hi"\n');

// compact and nested seq indentation (nested under a top-level key so the fragment survives the
// column-0 shape allowlist and actually reaches scanStructure through the full pipeline)
add('compact-key', 'note:\n  - key: value\n');
add('nested-compact-key', 'note:\n  - - key: value\n');
add('compact-key-block', 'note:\n  - key: |\n      body\n      [never closes\nb: 1\n');
add('nested-compact-key-block', 'note:\n  - - key: |\n        body\n        [never closes\nb: 1\n');

// flow plain scalars w/ mid-token quotes; tab-separated flow comment
add('flow-mid-quote', 'a: [abc"unterminated]\n');
add('flow-mid-squote', "a: [abc'unterminated]\n");
add('flow-tab-comment', 'a: [1,\t# }]\nb: 1\n');

// multi-line quotes / flows; '' escape
add('multiline-dq', 'a: "line one\n  line two"\nb: 2\n');
add('multiline-sq', "a: 'line one\n  line two'\nb: 2\n");
add('multiline-flow', 'a: [1,\n  2,\n  3]\nb: 2\n');
add('sq-escape', "a: 'it''s fine'\nb: 2\n");
add('dq-escape', 'a: "she said \\"hi\\""\nb: 2\n');
add('dq-backslash', 'a: "back\\\\slash"\nb: 2\n');
add('flow-wrap-plain', 'a: [abc\n  def]\n');

// a flow/quote continuation flush to COLUMN 0 (the Step 4 shape-allowlist fix this build shipped)
add('col0-flow-close', 'a: [1,\n2]\n');
add('col0-flow-close-deeper', 'a: [1, [2,\n3]]\n');
add('col0-dq-close', 'a: "l1\nl2"\nb: 2\n');
add('col0-sq-close', "a: 'l1\nl2'\nb: 2\n");
add('col0-flow-multi', 'a: [1,\n2,\n3]\nb: 2\n');
add('col0-flow-unterminated', 'a: [1,\n2\n');
add('col0-dq-unterminated', 'a: "l1\nl2\n');
add('col0-mixed', 'a: ["x",\n"y"]\nb: [3,\n4]\n');

// mismatched delimiter types — untyped floor never catches these (accepted false-negative), must not
// crash and must never falsely reject either
add('mismatch-bracket-brace', 'a: [1, 2}\n');
add('mismatch-brace-bracket', 'a: {x: 1]\n');

// shipped-example mutations
const shipped = `stack:
  backend:
    type: laravel
    route_globs:
      - "routes/web/*.php"
      - "routes/admin/*.php"
    api_url_prefix: "/api/v1"
capture:
  role_flags:
    admin:
      - AuthAdminUser
    # internal: []
    # external: []
  command: |
    docker compose run --rm \\
      --user "$(id -u):$(id -g)" \\
      app npx playwright test
  auth_role_enum: [admin, internal, external]
`;
add('shipped-verbatim', shipped);
add('shipped-drop-quote', shipped.replace('"routes/web/*.php"', '"routes/web/*.php'));
add('shipped-drop-bracket', shipped.replace('[admin, internal, external]', '[admin, internal, external'));
add('shipped-insert-alias', shipped.replace('type: laravel', 'type: *undefined'));
add('shipped-insert-anchor', shipped.replace('type: laravel', 'type: &t laravel'));
add('shipped-slip-indent', shipped.replace('      - AuthAdminUser', '     - AuthAdminUser'));
add('shipped-truncate-flow', shipped.replace('[admin, internal, external]', '[admin, internal'));
add('shipped-weaponize-comment', shipped.replace('# internal: []', '# internal: [AuthUser'));

// a comment starting with NO space right after a flow closer (post-#116 review round): once the
// outermost flow node closes, lexFlowChars must stop lexing the rest of the line — a `#` glued
// directly onto `]`/`}` is still a comment start even with no preceding whitespace, and its content
// (however bracket-shaped) must never be treated as live flow again. Closer type × tail, both at the
// top level and nested under a key, so the fragment exercises this dimension through the full
// column-0-shape-allowlist pipeline too.
const flowCloseShapes = ['[1]', '[]', '{}', '{a: 1}', '[[1]]'];
const flowCloseTails = ['#[', '#{', '#a: [b', '#TODO: see [42', '# balanced comment', ' #[']; // last two: controls
for (const closer of flowCloseShapes) {
  for (const tail of flowCloseTails) {
    add(`flowclose ${closer}${tail}`, `note: ${closer}${tail}\n`);
    add(`flowclose-nested ${closer}${tail}`, `outer:\n  note: ${closer}${tail}\n  b: 1\n`);
  }
}

// unicode-aware fragments
const NBSP = String.fromCharCode(0xa0);
const ASTRAL = String.fromCodePoint(0x1f600);
const EURO = '€';
const COMBINING = 'e' + String.fromCharCode(0x0301); // e + combining acute accent
add('unicode-nbsp-value', `a: "value${NBSP}here"\n`);
add('unicode-astral-value', `a: "${ASTRAL}"\n`);
add('unicode-euro', `currency: "${EURO}"\n`);
add('unicode-combining', `name: "${COMBINING}"\n`);

// randomized combinatorial generation across the same dimensions, seeded and reproducible
const dashPrefixes = ['', '- ', '- - ', '- - - '];
const seps = [': ', ':\t'];
const valueOpeners = ['[', '{', '"', "'", '*', '|', '>', 'plain'];
const closers = { '[': ']', '{': '}', '"': '"', "'": "'" };
for (let i = 0; i < 2200; i += 1) {
  const dash = pick(dashPrefixes);
  const sep = pick(seps);
  const opener = pick(valueOpeners);
  const closed = rand() < 0.5;
  let value;
  if (opener === 'plain') {
    value = pick(['hello', 'a*b', 'http://x:8080', 'text with spaces', '5" pipe', 'he said "hi"']);
  } else if (opener === '|' || opener === '>') {
    const mod = pick(['', '2', '-', '+']);
    value = `${opener}${mod}\n${' '.repeat(int(2, 8))}body line\n${' '.repeat(int(2, 8))}[ maybe open\n`;
  } else if (opener === '*') {
    value = closed ? 'x' : '';
  } else {
    const inner = pick(['1, 2', '"a", "b"', "'a', 'b'", '"x":"y"', 'a, [nested', '1, 2, 3']);
    value = closed ? `${opener}${inner}${closers[opener]}` : `${opener}${inner}`;
  }
  let doc;
  if (dash) {
    // nest under a top-level key so the fragment survives the column-0 shape allowlist and actually
    // reaches scanStructure through the full readProfileVersion pipeline (a bare "- ..." at column 0
    // is rejected earlier, for unrelated and already-proven-safe reasons).
    doc = `note:\n  ${dash}${value}\nb: 1\n`;
  } else if (rand() < 0.5) {
    doc = `k${sep}${value}\nb: 1\n`;
  } else {
    doc = `outer:\n  k${sep}${value}\n  b: 1\n`;
  }
  add(`rand${i}`, doc);
}

// ---- oracle: batch every fragment through ONE ruby process ----------------------------------------

const ORACLE_SCRIPT = `
require 'yaml'
require 'json'
frags = JSON.parse(File.read(ARGV[0]))
out = []
frags.each_with_index do |s, i|
  begin
    Psych.load(s)
    out << "#{i}\\tOK"
  rescue Exception => e
    out << "#{i}\\tRAISE\\t#{e.class}"
  end
end
puts out.join("\\n")
`;

function runOracle(fragments) {
  const dir = mkdtempSync(join(tmpdir(), 'profile-version-differential-'));
  try {
    const corpusPath = join(dir, 'corpus.json');
    const scriptPath = join(dir, 'oracle.rb');
    writeFileSync(corpusPath, JSON.stringify(fragments));
    writeFileSync(scriptPath, ORACLE_SCRIPT);
    const result = spawnSync('ruby', [scriptPath, corpusPath], {
      encoding: 'utf8',
      maxBuffer: 1024 * 1024 * 64,
    });
    assert.equal(result.status, 0, `ruby oracle failed: ${result.stderr}`);
    const status = new Array(fragments.length);
    for (const line of result.stdout.trim().split('\n')) {
      const [idxStr, verdict] = line.split('\t');
      status[Number(idxStr)] = verdict;
    }
    return status;
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

// ---- fatal assertions ------------------------------------------------------------------------------

test('differential fuzz: zero false-rejects across the full generated corpus', { skip: !RUBY_AVAILABLE }, () => {
  const oracleStatus = runOracle(frags);
  const violations = [];
  for (let i = 0; i < frags.length; i += 1) {
    const r = readProfileVersion(frags[i]);
    if (r.status === 'malformed' && oracleStatus[i] === 'OK') {
      violations.push({ label: labels[i], message: r.message, fragment: frags[i] });
    }
  }
  if (violations.length > 0) {
    const detail = violations
      .slice(0, 10)
      .map((v) => `  [${v.label}] ${v.message}\n    fragment=${JSON.stringify(v.fragment)}`)
      .join('\n');
    assert.fail(`${violations.length} false-reject(s) out of ${frags.length} fragments:\n${detail}`);
  }
  assert.equal(violations.length, 0);
});

test('differential fuzz: corpus size is large enough to be a meaningful gate', { skip: !RUBY_AVAILABLE }, () => {
  assert.ok(frags.length >= 2000, `corpus has only ${frags.length} fragments, expected >= 2000`);
});

test('differential fuzz: coverage — the known-invalid A/C representatives are still flagged', { skip: !RUBY_AVAILABLE }, () => {
  const mustFlag = {
    'unterminated flow (A1)': 'profile_version: 1\nroute_globs: ["a", "b"\n',
    'unterminated double quote (A3)': 'profile_version: 1\nname: "u\n',
    'unterminated single quote (A4)': "profile_version: 1\nsep: 'a\n",
    'undefined alias (C2 glob)': 'profile_version: 1\nglob: *.md\n',
    'undefined alias (C4 extra)': 'profile_version: 1\nextra: *undef\n',
    'undefined alias (C9 bare star)': 'profile_version: 1\nnote: * foo\n',
    'flow continuation, unterminated at column 0': 'profile_version: 1\na: [1,\n2\n',
  };
  for (const [label, doc] of Object.entries(mustFlag)) {
    const r = readProfileVersion(doc);
    assert.equal(r.status, 'malformed', `${label} did not get flagged: ${JSON.stringify(r)}`);
    assert.match(r.message, /structural:/, `${label} was flagged for a non-structural reason: ${r.message}`);
  }
});
